///<amd-module name="hr.form.bootstrap4"/>

import * as component from 'hr.components';
import {ComponentBuilder, VariantBuilder} from 'hr.componentbuilder';

var builder;

builder = new ComponentBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> {{if xUi.autocomplete}} <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="{{buildType}}" list="{{uniqueId}}-datalist"> <datalist id="{{uniqueId}}-datalist"></datalist> {{else}} <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="{{buildType}}"> {{/if}} </div> </div>');
builder.addVariant("date-time", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text"> </div> </div>'));
builder.addVariant("date", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text"> </div> </div>'));
builder.addVariant("textarea", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <textarea id="{{uniqueId}}" class="form-control" name="{{buildName}}" rows="{{size}}"></textarea> </div> </div>'));
builder.addVariant("checkbox", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-check mb-2"> <input type="checkbox" class="form-check-input" name="{{buildName}}" value="{{buildValue}}" id="{{uniqueId}}">&nbsp; <label class="form-check-label" for="{{uniqueId}}">{{title}}</label> </div> </div>'));
builder.addVariant("hidden", new VariantBuilder('<input id="{{uniqueId}}" type="hidden" name="{{buildName}}">'));
builder.addVariant("number", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="number" step="any"> </div> </div>'));
builder.addVariant("select", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <select id="{{uniqueId}}" class="form-control" name="{{buildName}}"> </select></div></div>'));
builder.addVariant("multiselect", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <select id="{{uniqueId}}" class="form-control" name="{{buildName}}" multiple="" size="{{size}}"> </select></div></div>'));
builder.addVariant("arrayEditor", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label>{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="card"> <div class="card-body"> <div data-hr-view="items" data-hr-view-component="hr.forms.default-arrayEditorItem"></div> <button type="button" class="btn btn-default" data-hr-on-click="add">Add</button> </div> </div> </div> </div>'));
builder.addVariant("multicheckbox", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label>{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="card" style="max-height:150px;overflow:auto;"> <div class="card-body pt-1 pb-1 pl-2 pr-2"> {{if xUi.selectAll}} <div class="form-check"><input type="checkbox" class="form-check-input" id="{{uniqueId}}-hr-multicheck-selectall" value="true" data-hr-on-click="selectAll" data-hr-handle="selectAll">&nbsp;<label class="form-check-label" for="{{uniqueId}}-hr-multicheck-selectall">Select All</label></div> {{/if}} <div data-hr-view="items" style="padding:0px;" data-hr-view-component="hr.forms.default-multicheckboxitem"></div> </div> </div> <div class="clearfix"></div> </div> </div>'));
builder.addVariant("radiobutton", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label>{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="card"> <div class="card-body pt-1 pb-1 pl-2 pr-2"> <div data-hr-view="items" data-hr-view-component="hr.forms.default-radiobutton"></div> </div> </div> </div> </div>'));
builder.addVariant("search", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}"> {{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span> </label> <div data-hr-on-focusout="stopSearch" data-hr-handle="searchFocusParent"> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text" data-hr-on-input="updateSearch"> <div class="dropdown" data-hr-toggle="popup" data-hr-class-on="open"> <ul class="dropdown-menu" data-hr-view="results" data-hr-view-component="hr.forms.default-searchResult"></ul> </div> </div> </div> </div>'));
component.register("hr.forms.default", builder);

builder = new ComponentBuilder('<div class="form-check"><input type="checkbox" class="form-check-input" value="{{value}}" data-hr-handle="check" id="{{uniqueId}}">&nbsp;<label class="form-check-label" for="{{uniqueId}}">{{label}}</label></div>');
component.register("hr.forms.default-multicheckboxitem", builder);

builder = new ComponentBuilder('<div class="form-check"><input type="radio" class="form-check-input" id="{{uniqueId}}" name="{{name}}" value="{{value}}" data-hr-handle="radio">&nbsp;<label class="form-check-label" for="{{uniqueId}}">{{label}}</label></div>');
component.register("hr.forms.default-radiobutton", builder);

builder = new ComponentBuilder('<div class="card mb-2"><div class="card-body"><button type="button" data-hr-on-click="remove" class="btn btn-default" data-hr-form-end="">Remove</button></div></div>');
component.register("hr.forms.default-arrayEditorItem", builder);

builder = new ComponentBuilder('<li><a href="#" data-hr-on-click="selectItem">{{title}}</a></li>');
builder.addVariant("message", new VariantBuilder('<li><a>{{title}}</a></li>'));
component.register("hr.forms.default-searchResult", builder);

builder = new ComponentBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> {{if xUi.autocomplete}} <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="{{buildType}}" list="{{uniqueId}}-datalist"> <datalist id="{{uniqueId}}-datalist"></datalist> {{else}} <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="{{buildType}}"> {{/if}} </div> </div> </div>');
builder.addVariant("date-time", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text"> </div> </div> </div>'));
builder.addVariant("date", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text"> </div> </div> </div>'));
builder.addVariant("textarea", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <textarea id="{{uniqueId}}" class="form-control" name="{{buildName}}" rows="{{size}}"></textarea> </div> </div> </div>'));
builder.addVariant("checkbox", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;" class="row mb-2"> <div class="col-sm-2"></div> <div class="col-sm-10"> <div class="form-check"> <input type="checkbox" class="form-check-input" name="{{buildName}}" value="{{buildValue}}" id="{{uniqueId}}">&nbsp; <label class="form-check-label" for="{{uniqueId}}">{{title}}</label> </div> </div> </div>'));
builder.addVariant("hidden", new VariantBuilder('<input type="hidden" name="{{buildName}}">'));
builder.addVariant("number", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="number" step="any"> </div> </div> </div>'));
builder.addVariant("select", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <select id="{{uniqueId}}" class="form-control" name="{{buildName}}"> </select></div></div></div>'));
builder.addVariant("multiselect", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label><div class="col-sm-10"> <select id="{{uniqueId}}" class="form-control" name="{{buildName}}" multiple="" size="{{size}}"> </select></div></div></div>'));
builder.addVariant("arrayEditor", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label class="col-sm-2">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <div class="card"> <div class="card-body pt-1 pb-1 pl-2 pr-2"> <div data-hr-view="items" data-hr-view-component="hr.forms.horizontal-arrayEditorItem"></div> <button type="button" class="btn btn-default" data-hr-on-click="add">Add</button> </div> </div> </div> </div> </div>'));
builder.addVariant("multicheckbox", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label class="col-sm-2">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10" style="max-height:150px;overflow:auto;"> <div class="card"> <div class="card-body pt-1 pb-1 pl-2 pr-2"> {{if xUi.selectAll}} <div style="padding:0px;"> <div class="form-check"><input type="checkbox" class="form-check-input" id="{{uniqueId}}-hr-multicheck-selectall" value="true" data-hr-on-click="selectAll" data-hr-handle="selectAll">&nbsp;<label class="form-check-label" for="{{uniqueId}}-hr-multicheck-selectall">Select All</label></div> </div> {{/if}} <div style="padding:0px;" data-hr-view="items" data-hr-view-component="hr.forms.horizontal-multicheckboxitem"></div> </div> </div> </div> <div class="clearfix"></div> </div> </div>'));
builder.addVariant("radiobutton", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label class="col-sm-2">{{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span></label> <div class="col-sm-10"> <div class="card"> <div class="card-body pt-1 pb-1 pl-2 pr-2" data-hr-view="items" data-hr-view-component="hr.forms.horizontal-radiobutton"></div> </div> </div> </div> </div>'));
builder.addVariant("search", new VariantBuilder('<div data-hr-toggle="{{buildName}}Hide" data-hr-style-on="display:none;"> <div class="form-group row" data-hr-toggle="{{buildName}}Error" data-hr-class-on="has-error"> <label for="{{uniqueId}}" class="col-sm-2 col-form-label"> {{title}}<span data-hr-view="{{buildName}}ErrorMessage" data-hr-toggle="{{buildName}}Error" data-hr-style-on="display:inline" style="display:none"> - {{{this}}}</span> </label> <div class="col-sm-10" data-hr-on-focusout="stopSearch" data-hr-handle="searchFocusParent"> <input id="{{uniqueId}}" class="form-control" name="{{buildName}}" type="text" data-hr-on-input="updateSearch"> <div class="dropdown" data-hr-toggle="popup" data-hr-class-on="open"> <ul class="dropdown-menu" data-hr-view="results" data-hr-view-component="hr.forms.horizontal-searchResult"></ul> </div> </div> </div> </div>'));
component.register("hr.forms.horizontal", builder);

builder = new ComponentBuilder('<div class="form-check"><input type="checkbox" class="form-check-input" value="{{value}}" data-hr-handle="check" id="{{uniqueId}}">&nbsp;<label class="form-check-label" for="{{uniqueId}}">{{label}}</label></div>');
component.register("hr.forms.horizontal-multicheckboxitem", builder);

builder = new ComponentBuilder('<div class="form-check"><input type="radio" class="form-check-input" id="{{uniqueId}}" name="{{name}}" value="{{value}}" data-hr-handle="radio">&nbsp;<label class="form-check-label" for="{{uniqueId}}">{{label}}</label></div>');
component.register("hr.forms.horizontal-radiobutton", builder);

builder = new ComponentBuilder('<div class="card mb-2"> <div class="card-body"> <button type="button" data-hr-on-click="remove" class="btn btn-default" data-hr-form-end="">Remove</button> </div> </div>');
component.register("hr.forms.horizontal-arrayEditorItem", builder);

builder = new ComponentBuilder('<li><a href="#" data-hr-on-click="selectItem">{{title}}</a></li>');
builder.addVariant("message", new VariantBuilder('<li><a>{{title}}</a></li>'));
component.register("hr.forms.horizontal-searchResult", builder);